import {
  Baby,
  Beer,
  BookOpen,
  Briefcase,
  Bus,
  CalendarDays,
  Car,
  Clapperboard,
  Coffee,
  CreditCard,
  Dog,
  Dumbbell,
  Droplets,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  Hammer,
  HeartPulse,
  Home,
  Landmark,
  Music,
  Pill,
  PiggyBank,
  Plane,
  Repeat,
  Shirt,
  ShoppingCart,
  Smartphone,
  TrendingDown,
  TrendingUp,
  Utensils,
  Wallet,
  Wifi,
  Wrench,
  Zap,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  "shopping-cart": ShoppingCart,
  "utensils": Utensils,
  "coffee": Coffee,
  "home": Home,
  "car": Car,
  "bus": Bus,
  "plane": Plane,
  "fuel": Fuel,
  "heart-pulse": HeartPulse,
  "pill": Pill,
  "graduation-cap": GraduationCap,
  "book-open": BookOpen,
  "briefcase": Briefcase,
  "gamepad-2": Gamepad2,
  "music": Music,
  "clapperboard": Clapperboard,
  "shirt": Shirt,
  "smartphone": Smartphone,
  "wifi": Wifi,
  "zap": Zap,
  "droplets": Droplets,
  "wrench": Wrench,
  "hammer": Hammer,
  "gift": Gift,
  "baby": Baby,
  "dog": Dog,
  "dumbbell": Dumbbell,
  "beer": Beer,
  "credit-card": CreditCard,
  "piggy-bank": PiggyBank,
  "landmark": Landmark,
  "wallet": Wallet,
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  "repeat": Repeat,
  "calendar-days": CalendarDays,
};

export function getCategoryIcon(name: string | null | undefined): LucideIcon | null {
  if (!name) return null;
  return CATEGORY_ICONS[name] ?? null;
}
