"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _dashboard from './dashboard.bones.json'
import _crud_list from './crud-list.bones.json'

configureBoneyard({"color":"#e7e5e1","darkColor":"#2a2a28","animate":"pulse"})

registerBones({
  "dashboard": _dashboard,
  "crud-list": _crud_list,
})
